/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex('questions').del();
    await knex('questions').insert([
        {question_id:1, subject_id:1, question:`What does HTML stand for?`},
        {question_id:2, subject_id:1, question:`Which HTML element is used to define the structure of an HTML `},
        {question_id:3, subject_id:1, question:`What is the correct HTML tag for creating an ordered list?`},
        {question_id:4, subject_id:1, question:`Which HTML tag is used for creating a hyperlink?`},
        {question_id:5, subject_id:1, question:`What is the purpose of the HTML <meta> tag?`},
        {question_id:6, subject_id:1, question:`Which HTML tag is used to insert a line break within a paragraph?`},
        {question_id:7, subject_id:1, question:`How do you comment out multiple lines in HTML?`},
        {question_id:8, subject_id:1, question:`Which HTML tag is used to define the title of a webpage?`},
        {question_id:9, subject_id:1, question:`What is the purpose of the HTML <iframe> element?`},
        {question_id:10, subject_id:1, question:`Which attribute is used to specify the character encoding for an HTML document?`},
        {question_id:11, subject_id:1, question:`What HTML tag is used to create a hyperlink to send an email?`},
        {question_id:12, subject_id:1, question:`Which HTML element is used to define a table row?`},
        {question_id:13, subject_id:1, question:`What is the purpose of the HTML <div> element?`},
        {question_id:14, subject_id:1, question:`Which HTML tag is used to define a bulleted list?`},
        {question_id:15, subject_id:1, question:`What is the correct HTML tag for inserting a line break?`},
        {question_id:16, subject_id:1, question:`Which HTML attribute is used to provide alternative text for images?`},
        {question_id:17, subject_id:1, question:`What does the HTML <form> element do?`},
        {question_id:18, subject_id:1, question:`Which HTML element is used to define the structure of an HTML document's body content?`},
        {question_id:19, subject_id:1, question:`What is the purpose of the HTML <input> element with type="checkbox"?`},
        {question_id:20, subject_id:1, question:`Which HTML tag is used to create a numbered list?`},
        {question_id:21, subject_id:2, question:`What does CSS stand for?`},
        {question_id:22, subject_id:2, question:`Which CSS property is used to change the text color of an element?`},
        {question_id:23, subject_id:2, question:`How do you include an external CSS file in an HTML document?`},
        {question_id:24, subject_id:2, question:`Which CSS property is used to set the background color of an element?`},
        {question_id:25, subject_id:2, question:`How do you include an external CSS file in an HTML document?`},
        {question_id:26, subject_id:2, question:`Which CSS property is used to set the background color of an element?`},
        {question_id:27, subject_id:2, question:`How do you select an element with the id "example" in CSS?`},
        {question_id:28, subject_id:2, question:`What is the default value of the "position" property in CSS?`},
        {question_id:29, subject_id:2, question:`Which CSS property is used to add space outside the border of an element?`},
        {question_id:30, subject_id:2, question:`Which CSS property is used to make text bold?`},
        {question_id:31, subject_id:2, question:`What is the CSS pseudo-class used to select the first child of an element?`},
        {question_id:32, subject_id:2, question:`How do you group multiple CSS selectors to apply the same styles to all of them?`},
        {question_id:33, subject_id:2, question:`Which CSS property is used to control the spacing between lines of text within an element?`},
        {question_id:34, subject_id:2, question:`What does CSS specificity determine?`},
        {question_id:35, subject_id:2, question:`Which CSS property is used to hide an element but reserve space for it in the layout?`},
        {question_id:36, subject_id:2, question:`Which CSS property is used to create a shadow effect behind an element?`},
        {question_id:37, subject_id:2, question:`What does the CSS property "float" do?`},
        {question_id:38, subject_id:2, question:`Which CSS property is used to control the order of flex items in a flex container?`},
        {question_id:39, subject_id:2, question:`What does the CSS property "z-index" control?`},
        {question_id:40, subject_id:2, question:`How can you center an element horizontally in CSS?`},
        {question_id:41, subject_id:3, question:`What does SCSS stand for?`},
        {question_id:42, subject_id:3, question:`In SCSS, what symbol is used to denote a nested block of code?`},
        {question_id:43, subject_id:3, question:`Which SCSS function is used to perform mathematical calculations?`},
        {question_id:44, subject_id:3, question:`In SCSS, what is the purpose of the @import directive?`},
        {question_id:45, subject_id:3, question:`What does the $ symbol indicate in SCSS?`},
        {question_id:46, subject_id:3, question:`Which SCSS feature allows you to reuse blocks of styles across your stylesheet?`},
        {question_id:47, subject_id:3, question:`What is the purpose of the @extend directive in SCSS?`},
        {question_id:48, subject_id:3, question:`Which SCSS data type represents a collection of values?`},
        {question_id:49, subject_id:3, question:`In SCSS, how can you comment out a single line of code?`},
        {question_id:50, subject_id:3, question:`What is the purpose of the !default flag when defining SCSS variables?`},
        {question_id:51, subject_id:3, question:`Which operator is used for concatenating strings in SCSS?`},
        {question_id:52, subject_id:3, question:`What is the output of the SCSS code: border: 1px solid darken(#3498db, 10%);?`},
        {question_id:53, subject_id:3, question:`In SCSS, what is the purpose of the @mixin directive?`},
        {question_id:54, subject_id:3, question:`What does the @for directive in SCSS allow you to do?`},
        {question_id:55, subject_id:3, question:`Which SCSS function can be used to generate a random number?`},
        {question_id:56, subject_id:3, question:`What is the purpose of the @if directive in SCSS?`},
        {question_id:57, subject_id:3, question:`Which SCSS feature allows you to group related styles together for better organization?`},
        {question_id:58, subject_id:3, question:`In SCSS, how can you import an external SCSS file located in a different directory?`},
        {question_id:59, subject_id:3, question:`What is the purpose of the @media directive in SCSS?`},
        {question_id:60, subject_id:3, question:`Which SCSS feature allows you to define a set of styles that can be `},
        {question_id:61, subject_id:4, question:`What does JavaScript primarily provide to a web page?`},
        {question_id:62, subject_id:4, question:`How do you declare a variable in JavaScript?`},
        {question_id:63, subject_id:4, question:`What is the purpose of the typeof operator in JavaScript?`},
        {question_id:64, subject_id:4, question:`Which of the following is not a JavaScript data type?`},
        {question_id:65, subject_id:4, question:`What will be the result of 5 + "5" in JavaScript?`},
        {question_id:66, subject_id:4, question:`How can you comment a single line in JavaScript?`},
        {question_id:67, subject_id:4, question:`Which loop is used for iterating through the properties of an object?`},
        {question_id:68, subject_id:4, question:`What is the purpose of the addEventListener method in JavaScript?`},
        {question_id:69, subject_id:4, question:`How do you declare a function in JavaScript?`},
        {question_id:70, subject_id:4, question:`What is the difference between null and undefined in JavaScript?`},
        {question_id:71, subject_id:4, question:`How can you check the length of an array called myArray in JavaScript?`},
        {question_id:72, subject_id:4, question:`What does the this keyword refer to in JavaScript?`},
        {question_id:73, subject_id:4, question:`How do you remove an element from an array in JavaScript?`},
        {question_id:74, subject_id:4, question:`What is a closure in JavaScript?`},
        {question_id:75, subject_id:4, question:`What does the JSON.parse() function do in JavaScript?`},
        {question_id:76, subject_id:4, question:`How do you stop the execution of a loop in JavaScript?`},
        {question_id:77, subject_id:4, question:`Which JavaScript method is used to sort elements in an array?`},
        {question_id:78, subject_id:4, question:`What is the purpose of the localStorage object in JavaScript?`},
        {question_id:79, subject_id:4, question:`What is a callback function in JavaScript?`},
        {question_id:80, subject_id:4, question:`Which symbol is used for single-line comments in JavaScript?`},
        {question_id:81, subject_id:5, question:`What is React?`},
        {question_id:82, subject_id:5, question:`Which company developed React?`},
        {question_id:83, subject_id:5, question:`What is JSX in React?`},
        {question_id:84, subject_id:5, question:`In React, what is the purpose of the render() method?`},
        {question_id:85, subject_id:5, question:`What is a component in React?`},
        {question_id:86, subject_id:5, question:`What is the virtual DOM in React?`},
        {question_id:87, subject_id:5, question:`What is the purpose of state in a React component?`},
        {question_id:88, subject_id:5, question:`How can you pass data from a parent component to a child component in React?`},
        {question_id:89, subject_id:5, question:`What is a controlled component in React?`},
        {question_id:90, subject_id:5, question:`What's the purpose of the componentDidMount() lifecycle method in React?`},
        {question_id:91, subject_id:5, question:`Which React feature allows you to reuse component logic without inheritance?`},
        {question_id:92, subject_id:5, question:`What is Redux used for in a React application?`},
        {question_id:93, subject_id:5, question:`What is the purpose of the useState hook in React?`},
        {question_id:94, subject_id:5, question:`In React Router, how do you define a route that matches any path?`},
        {question_id:95, subject_id:5, question:`What is the purpose of the map function when rendering a list of items in React?`},
        {question_id:96, subject_id:5, question:`How can you prevent a React component from re-rendering unnecessarily?`},
        {question_id:97, subject_id:5, question:`What is the purpose of the key prop in a list of elements in React?`},
        {question_id:98, subject_id:5, question:`Which tool can you use to inspect and debug React applications?`},
        {question_id:99, subject_id:5, question:`What is the purpose of the componentWillUnmount() lifecycle method in React?`},
        {question_id:100, subject_id:5, question:`Which React library is commonly used for managing forms and form state?`},
        {question_id:101, subject_id:6, question:`What does SQL stand for?`},
        {question_id:102, subject_id:6, question:`Which command is used to select all columns from a table named "customers"?`},
        {question_id:103, subject_id:6, question:`Which MySQL clause is used to filter the results of a SELECT statement?`},
        {question_id:104, subject_id:6, question:`What is the purpose of the SQL JOIN clause?`},
        {question_id:105, subject_id:6, question:`Which data type is used to store a date in MySQL?`},
        {question_id:106, subject_id:6, question:`In MySQL, which statement is used to update existing records in a table?`},
        {question_id:107, subject_id:6, question:`What is the primary key used for in a MySQL table?`},
        {question_id:108, subject_id:6, question:`Which SQL statement is used to add new rows of data to a table?`},
        {question_id:109, subject_id:6, question:`What is the purpose of the MySQL "LIMIT" clause?`},
        {question_id:110, subject_id:6, question:`What is the result of using the SQL "COUNT" function?`},
        {question_id:111, subject_id:6, question:`Which SQL statement is used to delete data from a database?`},
        {question_id:112, subject_id:6, question:`What does the SQL "ORDER BY" clause do?`},
        {question_id:113, subject_id:6, question:`Which SQL command is used to remove a table from a database?`},
        {question_id:114, subject_id:6, question:`What is the purpose of the SQL "DISTINCT" keyword?`},
        {question_id:115, subject_id:6, question:`Which SQL function is used to find the highest value in a column?`},
        {question_id:116, subject_id:6, question:`What is the default port number for MySQL?`},
        {question_id:117, subject_id:6, question:`Which SQL statement is used to change data in an existing table structure?`},
        {question_id:118, subject_id:6, question:`What is the purpose of the SQL "LIKE" operator?`},
        {question_id:119, subject_id:6, question:`Which SQL command is used to create a new database?`},
        {question_id:120, subject_id:6, question:`What is a foreign key in MySQL?`}
    ]);
};