/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('responses').del();
  await knex('responses').insert([
    {response_id:1, question_id:1, response:`Hyperlink Text Markup Language`, is_correct:false},
    {response_id:2, question_id:1, response:`Hypertext Transfer Markup Language`, is_correct:true},
    {response_id:3, question_id:1, response:`Hyper Text Makeup Language`, is_correct:false},
    {response_id:4, question_id:1, response:`High-Level Text Markup Language`, is_correct:false},
    {response_id:1, question_id:2, response:`"header"`, is_correct:false},
    {response_id:2, question_id:2, response:` "body"`, is_correct:false},
    {response_id:3, question_id:2, response:`"html"`, is_correct:true},
    {response_id:4, question_id:2, response:`"main"`, is_correct:false},
    {response_id:1, question_id:3, response:`"ul"`, is_correct:false},
    {response_id:2, question_id:3, response:`"list"`, is_correct:false},
    {response_id:3, question_id:3, response:`"ol"`, is_correct:true},
    {response_id:4, question_id:3, response:`"li"`, is_correct:false},
    {response_id:1, question_id:4, response:`"link"`, is_correct:true},
    {response_id:2, question_id:4, response:`"a"`, is_correct:false},
    {response_id:3, question_id:4, response:`"href"`, is_correct:false},
    {response_id:4, question_id:4, response:` "url"`, is_correct:false},
    {response_id:1, question_id:5, response:` To define a paragraph`, is_correct:false},
    {response_id:2, question_id:5, response:`To provide metadata about the document`, is_correct:true},
    {response_id:3, question_id:5, response:`To create a line break`, is_correct:false},
    {response_id:4, question_id:5, response:`To define a hyperlink`, is_correct:false},
    {response_id:1, question_id:6, response:`"br"`, is_correct:true},
    {response_id:2, question_id:6, response:`"lb"`, is_correct:false},
    {response_id:3, question_id:6, response:`"newline"`, is_correct:false},
    {response_id:4, question_id:6, response:`"break"`, is_correct:false},
    {response_id:1, question_id:7, response:`"!-- This is a comment --"`, is_correct:true},
    {response_id:2, question_id:7, response:`// This is a comment //`, is_correct:false},
    {response_id:3, question_id:7, response:`* This is a comment */`, is_correct:false},
    {response_id:4, question_id:7, response:`** This is a comment **`, is_correct:false},
    {response_id:1, question_id:8, response:`"header"`, is_correct:false},
    {response_id:2, question_id:8, response:` "title"`, is_correct:true},
    {response_id:3, question_id:8, response:` "h1"`, is_correct:false},
    {response_id:4, question_id:8, response:`"head"`, is_correct:false},
    {response_id:1, question_id:9, response:`To insert an image`, is_correct:false},
    {response_id:2, question_id:9, response:`To create a clickable button`, is_correct:false},
    {response_id:3, question_id:9, response:`To embed external content like a video or map`, is_correct:true},
    {response_id:4, question_id:9, response:`To define a list`, is_correct:false},
    {response_id:1, question_id:10, response:`charset`, is_correct:true},
    {response_id:2, question_id:10, response:`encoding`, is_correct:false},
    {response_id:3, question_id:10, response:`content-type`, is_correct:false},
    {response_id:4, question_id:10, response:`language`, is_correct:false},
    {response_id:1, question_id:11, response:`"email"`, is_correct:false},
    {response_id:2, question_id:11, response:`"mail"`, is_correct:false},
    {response_id:3, question_id:11, response:`"a href="mailto:email@example.com""`, is_correct:true},
    {response_id:4, question_id:11, response:`"link href="email@example.com""`, is_correct:false},
    {response_id:1, question_id:12, response:`"td"`, is_correct:false},
    {response_id:2, question_id:12, response:`"tr"`, is_correct:true},
    {response_id:3, question_id:12, response:`"table"`, is_correct:false},
    {response_id:4, question_id:12, response:`"th"`, is_correct:false},
    {response_id:1, question_id:13, response:`To define a division or section of a webpage`, is_correct:true},
    {response_id:2, question_id:13, response:`To create a hyperlink`, is_correct:false},
    {response_id:3, question_id:13, response:`To insert a line break`, is_correct:false},
    {response_id:4, question_id:13, response:`To define a list`, is_correct:false},
    {response_id:1, question_id:14, response:`"ul"`, is_correct:true},
    {response_id:2, question_id:14, response:`"list"`, is_correct:false},
    {response_id:3, question_id:14, response:`"ol"`, is_correct:false},
    {response_id:4, question_id:14, response:`"li"`, is_correct:false},
    {response_id:1, question_id:15, response:`"line"`, is_correct:false},
    {response_id:2, question_id:15, response:`"break"`, is_correct:false},
    {response_id:3, question_id:15, response:`"br"`, is_correct:true},
    {response_id:4, question_id:15, response:`"newline"`, is_correct:false},
    {response_id:1, question_id:16, response:`alt`, is_correct:true},
    {response_id:2, question_id:16, response:`text`, is_correct:false},
    {response_id:3, question_id:16, response:`description`, is_correct:false},
    {response_id:4, question_id:16, response:`img-alt`, is_correct:false},
    {response_id:1, question_id:17, response:`It defines a section of the webpage.`, is_correct:false},
    {response_id:2, question_id:17, response:`It defines a hyperlink.`, is_correct:false},
    {response_id:3, question_id:17, response:` It creates a clickable button.`, is_correct:false},
    {response_id:4, question_id:17, response:`It defines an interactive form for user input.`, is_correct:true},
    {response_id:1, question_id:18, response:`"head"`, is_correct:false},
    {response_id:2, question_id:18, response:`"main"`, is_correct:false},
    {response_id:3, question_id:18, response:`"body"`, is_correct:true},
    {response_id:4, question_id:18, response:`"section"`, is_correct:false},
    {response_id:1, question_id:19, response:`To create a radio button`, is_correct:false},
    {response_id:2, question_id:19, response:`To insert a text input field`, is_correct:false},
    {response_id:3, question_id:19, response:`To create a checkbox for multiple selections`, is_correct:true},
    {response_id:4, question_id:19, response:`To define a dropdown menu`, is_correct:false},
    {response_id:1, question_id:20, response:`"ul"`, is_correct:false},
    {response_id:2, question_id:20, response:`"list"`, is_correct:false},
    {response_id:3, question_id:20, response:`"ol"`, is_correct:true},
    {response_id:4, question_id:20, response:`"li"`, is_correct:false},
    {response_id:1, question_id:21, response:`Computer Style Sheets`, is_correct:false},
    {response_id:2, question_id:21, response:`Creative Style Sheets`, is_correct:false},
    {response_id:3, question_id:21, response:`Cascading Style Sheets`, is_correct:true},
    {response_id:4, question_id:21, response:`Complex Style Sheets`, is_correct:false},
    {response_id:1, question_id:22, response:`text-color`, is_correct:false},
    {response_id:2, question_id:22, response:`font-color`, is_correct:false},
    {response_id:3, question_id:22, response:`color`, is_correct:true},
    {response_id:4, question_id:22, response:`text-style`, is_correct:false},
    {response_id:1, question_id:23, response:`Using the "style" tag`, is_correct:false},
    {response_id:2, question_id:23, response:`Using the "link" tag`, is_correct:true},
    {response_id:3, question_id:23, response:`Using the "css" tag`, is_correct:false},
    {response_id:4, question_id:23, response:`Using the "external-css" tag`, is_correct:false},
    {response_id:1, question_id:24, response:`background-color`, is_correct:true},
    {response_id:2, question_id:24, response:`color-background`, is_correct:false},
    {response_id:3, question_id:24, response:`background-style`, is_correct:false},
    {response_id:4, question_id:24, response:`bgcolor`, is_correct:false},
    {response_id:1, question_id:25, response:`#element.example`, is_correct:false},
    {response_id:2, question_id:25, response:`.element#example`, is_correct:false},
    {response_id:3, question_id:25, response:`#example`, is_correct:true},
    {response_id:4, question_id:25, response:`.example`, is_correct:false},
    {response_id:1, question_id:26, response:`static`, is_correct:true},
    {response_id:2, question_id:26, response:`relative`, is_correct:false},
    {response_id:3, question_id:26, response:`absolute`, is_correct:false},
    {response_id:4, question_id:26, response:`fixed`, is_correct:false},
    {response_id:1, question_id:27, response:`margin`, is_correct:true},
    {response_id:2, question_id:27, response:`padding`, is_correct:false},
    {response_id:3, question_id:27, response:`border-spacing`, is_correct:false},
    {response_id:4, question_id:27, response:`spacing`, is_correct:false},
    {response_id:1, question_id:28, response:`font-weight`, is_correct:true},
    {response_id:2, question_id:28, response:`text-style`, is_correct:false},
    {response_id:3, question_id:28, response:`font-bold`, is_correct:false},
    {response_id:4, question_id:28, response:`bold-text`, is_correct:false},
    {response_id:1, question_id:29, response:`:first-child`, is_correct:true},
    {response_id:2, question_id:29, response:`:child-first`, is_correct:false},
    {response_id:3, question_id:29, response:`:first`, is_correct:false},
    {response_id:4, question_id:29, response:`:first-of-type`, is_correct:false},
    {response_id:1, question_id:30, response:`Separate them with a comma (,)`, is_correct:true},
    {response_id:2, question_id:30, response:`Separate them with a plus sign (+)`, is_correct:false},
    {response_id:3, question_id:30, response:`Separate them with a hyphen (-)`, is_correct:false},
    {response_id:4, question_id:30, response:`Separate them with a semicolon (;)`, is_correct:false},
    {response_id:1, question_id:31, response:`line-height`, is_correct:true},
    {response_id:2, question_id:31, response:`text-spacing`, is_correct:false},
    {response_id:3, question_id:31, response:`line-spacing`, is_correct:false},
    {response_id:4, question_id:31, response:`text-line`, is_correct:false},
    {response_id:1, question_id:32, response:`The order in which styles are applied`, is_correct:false},
    {response_id:2, question_id:32, response:`The size of text`, is_correct:false},
    {response_id:3, question_id:32, response:`Which style rules take precedence`, is_correct:true},
    {response_id:4, question_id:32, response:`The color of text`, is_correct:false},
    {response_id:1, question_id:33, response:`display: hidden`, is_correct:false},
    {response_id:2, question_id:33, response:`visibility: hidden`, is_correct:false},
    {response_id:3, question_id:33, response:`opacity: 0`, is_correct:false},
    {response_id:4, question_id:33, response:`display: none`, is_correct:true},
    {response_id:1, question_id:34, response:`shadow-effect`, is_correct:false},
    {response_id:2, question_id:34, response:`box-shadow`, is_correct:true},
    {response_id:3, question_id:34, response:`text-shadow`, is_correct:false},
    {response_id:4, question_id:34, response:`element-shadow`, is_correct:false},
    {response_id:1, question_id:35, response:`Makes text float on the water`, is_correct:false},
    {response_id:2, question_id:35, response:`Removes an element from the flow of the document`, is_correct:true},
    {response_id:3, question_id:35, response:`Changes the font style`, is_correct:false},
    {response_id:4, question_id:35, response:`Sets an element's position to fixed`, is_correct:false},
    {response_id:1, question_id:36, response:`flex-direction`, is_correct:false},
    {response_id:2, question_id:36, response:`order`, is_correct:true},
    {response_id:3, question_id:36, response:`flex-order`, is_correct:false},
    {response_id:4, question_id:36, response:`item-order`, is_correct:false},
    {response_id:1, question_id:37, response:`The size of an element`, is_correct:false},
    {response_id:2, question_id:37, response:`The position of an element relative to its parent`, is_correct:true},
    {response_id:3, question_id:37, response:`The font size`, is_correct:false},
    {response_id:4, question_id:37, response:`The color of text`, is_correct:false},
    {response_id:1, question_id:38, response:`text-align: center`, is_correct:false},
    {response_id:2, question_id:38, response:`margin: auto`, is_correct:false},
    {response_id:3, question_id:38, response:`align: center`, is_correct:false},
    {response_id:4, question_id:38, response:`display: center`, is_correct:true},
    {response_id:1, question_id:39, response:`border-curve`, is_correct:false},
    {response_id:2, question_id:39, response:`corner-radius`, is_correct:false},
    {response_id:3, question_id:39, response:`border-radius`, is_correct:true},
    {response_id:4, question_id:39, response:`rounded-border`, is_correct:false},
    {response_id:1, question_id:40, response:`To change the font size of text`, is_correct:false},
    {response_id:2, question_id:40, response:`To apply different styles based on the screen size or device`, is_correct:true},
    {response_id:3, question_id:40, response:`To change the background color of an element`, is_correct:false},
    {response_id:4, question_id:40, response:`To create animations`, is_correct:false},
    {response_id:1, question_id:41, response:`Sassy Cascading Style Sheets`, is_correct:true},
    {response_id:2, question_id:41, response:`Scalable Cascading Style Sheets`, is_correct:false},
    {response_id:3, question_id:41, response:`Simple Cascading Style Sheets`, is_correct:false},
    {response_id:4, question_id:41, response:`Styled Cascading Style Sheets`, is_correct:false},
    {response_id:1, question_id:42, response:`"{}"`, is_correct:true},
    {response_id:2, question_id:42, response:`"()"`, is_correct:false},
    {response_id:3, question_id:42, response:`"[]"`, is_correct:false},
    {response_id:4, question_id:42, response:`"&"`, is_correct:false},
    {response_id:1, question_id:43, response:`calc()`, is_correct:true},
    {response_id:2, question_id:43, response:`math()`, is_correct:false},
    {response_id:3, question_id:43, response:`calculate()`, is_correct:false},
    {response_id:4, question_id:43, response:`sum()`, is_correct:false},
    {response_id:1, question_id:44, response:`To include external JavaScript files`, is_correct:false},
    {response_id:2, question_id:44, response:`To include external CSS files`, is_correct:false},
    {response_id:3, question_id:44, response:`To include another SCSS file`, is_correct:true},
    {response_id:4, question_id:44, response:`To declare variables`, is_correct:false},
    {response_id:1, question_id:45, response:`Comments`, is_correct:false},
    {response_id:2, question_id:45, response:`Mixins`, is_correct:false},
    {response_id:3, question_id:45, response:`Variables`, is_correct:true},
    {response_id:4, question_id:45, response:`Functions`, is_correct:false},
    {response_id:1, question_id:46, response:`Variables`, is_correct:false},
    {response_id:2, question_id:46, response:`Mixins`, is_correct:true},
    {response_id:3, question_id:46, response:`Functions`, is_correct:false},
    {response_id:4, question_id:46, response:`Classes`, is_correct:false},
    {response_id:1, question_id:47, response:`To create a new class`, is_correct:false},
    {response_id:2, question_id:47, response:`To include external libraries`, is_correct:false},
    {response_id:3, question_id:47, response:`To share styles between selectors`, is_correct:true},
    {response_id:4, question_id:47, response:`To import images`, is_correct:false},
    {response_id:1, question_id:48, response:`Numbers`, is_correct:false},
    {response_id:2, question_id:48, response:`Lists`, is_correct:true},
    {response_id:3, question_id:48, response:`Strings`, is_correct:false},
    {response_id:4, question_id:48, response:`Colors`, is_correct:false},
    {response_id:1, question_id:49, response:`/* This is a comment */`, is_correct:true},
    {response_id:2, question_id:49, response:`// This is a comment`, is_correct:false},
    {response_id:3, question_id:49, response:` This is a comment`, is_correct:false},
    {response_id:4, question_id:49, response:`# This is a comment`, is_correct:false},
    {response_id:1, question_id:50, response:`It makes the variable immutable.`, is_correct:false},
    {response_id:2, question_id:50, response:`It sets a default value if the variable is undefined.`, is_correct:true},
    {response_id:3, question_id:50, response:`It creates a global variable.`, is_correct:false},
    {response_id:4, question_id:50, response:`It makes the variable inheritable.`, is_correct:false},
    {response_id:1, question_id:51, response:`"+"`, is_correct:true},
    {response_id:2, question_id:51, response:`"-"`, is_correct:false},
    {response_id:3, question_id:51, response:`"*"`, is_correct:false},
    {response_id:4, question_id:51, response:`"/"`, is_correct:false},
    {response_id:1, question_id:52, response:`A border with a color 10% darker than #3498db`, is_correct:true},
    {response_id:2, question_id:52, response:`A border with a color #3498db`, is_correct:false},
    {response_id:3, question_id:52, response:`A border with a color 10% lighter than #3498db`, is_correct:false},
    {response_id:4, question_id:52, response:`An error`, is_correct:false},
    {response_id:1, question_id:53, response:`To define a function`, is_correct:true},
    {response_id:2, question_id:53, response:`To create a loop`, is_correct:false},
    {response_id:3, question_id:53, response:`To include external stylesheets`, is_correct:false},
    {response_id:4, question_id:53, response:`To define a class`, is_correct:false},
    {response_id:1, question_id:54, response:`Define a loop`, is_correct:true},
    {response_id:2, question_id:54, response:`Import fonts`, is_correct:false},
    {response_id:3, question_id:54, response:`Create a new class`, is_correct:false},
    {response_id:4, question_id:54, response:`Define a mixin`, is_correct:false},
    {response_id:1, question_id:55, response:`random()`, is_correct:false},
    {response_id:2, question_id:55, response:`generateRandom()`, is_correct:false},
    {response_id:3, question_id:55, response:`rand()`, is_correct:true},
    {response_id:4, question_id:55, response:`randomNumber()`, is_correct:false},
    {response_id:1, question_id:56, response:`To define a variable`, is_correct:false},
    {response_id:2, question_id:56, response:`To create a loop`, is_correct:false},
    {response_id:3, question_id:56, response:`To conditionally apply styles`, is_correct:true},
    {response_id:4, question_id:56, response:`To include external files`, is_correct:false},
    {response_id:1, question_id:57, response:`Variables`, is_correct:false},
    {response_id:2, question_id:57, response:`Mixins`, is_correct:false},
    {response_id:3, question_id:57, response:`Nesting`, is_correct:true},
    {response_id:4, question_id:57, response:`Functions`, is_correct:false},
    {response_id:1, question_id:58, response:`@import "styles/mystyles";`, is_correct:false},
    {response_id:2, question_id:58, response:`@import "./mystyles";`, is_correct:false},
    {response_id:3, question_id:58, response:`@import "../styles/mystyles";`, is_correct:true},
    {response_id:4, question_id:58, response:`@import "mystyles.scss";`, is_correct:false},
    {response_id:1, question_id:59, response:`To define a variable`, is_correct:false},
    {response_id:2, question_id:59, response:`To create a loop`, is_correct:false},
    {response_id:3, question_id:59, response:`To apply styles based on screen size or media type`, is_correct:true},
    {response_id:4, question_id:59, response:`To include external files`, is_correct:false},
    {response_id:1, question_id:60, response:`Variables`, is_correct:false},
    {response_id:2, question_id:60, response:`Mixins`, is_correct:true},
    {response_id:3, question_id:60, response:`Functions`, is_correct:false},
    {response_id:4, question_id:60, response:`Classes`, is_correct:false},
    {response_id:1, question_id:61, response:`Styling`, is_correct:false},
    {response_id:2, question_id:61, response:`Interactivity`, is_correct:true},
    {response_id:3, question_id:61, response:`Structure`, is_correct:false},
    {response_id:4, question_id:61, response:`Animation`, is_correct:false},
    {response_id:1, question_id:62, response:`v myVar = 5;`, is_correct:false},
    {response_id:2, question_id:62, response:`let myVar = 5;`, is_correct:true},
    {response_id:3, question_id:62, response:`const myVar = 5;`, is_correct:false},
    {response_id:4, question_id:62, response:`variable myVar = 5;`, is_correct:false},
    {response_id:1, question_id:63, response:`It returns the data type of a variable or expression.`, is_correct:true},
    {response_id:2, question_id:63, response:`It defines a new variable.`, is_correct:false},
    {response_id:3, question_id:63, response:`It performs mathematical operations.`, is_correct:false},
    {response_id:4, question_id:63, response:`It creates a new function.`, is_correct:false},
    {response_id:1, question_id:64, response:`String`, is_correct:false},
    {response_id:2, question_id:64, response:`Float`, is_correct:true},
    {response_id:3, question_id:64, response:`Boolean`, is_correct:false},
    {response_id:4, question_id:64, response:`Number`, is_correct:false},
    {response_id:1, question_id:65, response:`10`, is_correct:false},
    {response_id:2, question_id:65, response:`"55"`, is_correct:true},
    {response_id:3, question_id:65, response:`55`, is_correct:false},
    {response_id:4, question_id:65, response:`Error`, is_correct:false},
    {response_id:1, question_id:66, response:`// This is a comment`, is_correct:true},
    {response_id:2, question_id:66, response:`/* This is a comment */`, is_correct:false},
    {response_id:3, question_id:66, response:`'' This is a comment '''`, is_correct:false},
    {response_id:4, question_id:66, response:`%% This is a comment %%`, is_correct:false},
    {response_id:1, question_id:67, response:`for loop`, is_correct:false},
    {response_id:2, question_id:67, response:`while loop`, is_correct:false},
    {response_id:3, question_id:67, response:`for...in loop`, is_correct:true},
    {response_id:4, question_id:67, response:`do...while loop`, is_correct:false},
    {response_id:1, question_id:68, response:`To add a new element to the page`, is_correct:false},
    {response_id:2, question_id:68, response:`To remove an element from the page`, is_correct:false},
    {response_id:3, question_id:68, response:`To bind a function to an event on an element`, is_correct:true},
    {response_id:4, question_id:68, response:`To create a new event in JavaScript`, is_correct:false},
    {response_id:1, question_id:69, response:`function: myFunction() {}`, is_correct:false},
    {response_id:2, question_id:69, response:`def myFunction() {}`, is_correct:false},
    {response_id:3, question_id:69, response:`function myFunction() {}`, is_correct:true},
    {response_id:4, question_id:69, response:`myFunction() => {}`, is_correct:false},
    {response_id:1, question_id:70, response:`They are the same thing.`, is_correct:false},
    {response_id:2, question_id:70, response:`null represents an intentionally empty or non-existent value, while undefined represents an uninitialized variable.`, is_correct:true},
    {response_id:3, question_id:70, response:`undefined represents an intentionally empty or non-existent value, while null represents an uninitialized variable.`, is_correct:false},
    {response_id:4, question_id:70, response:`undefined is used to terminate a function, while null is used to exit a loop.`, is_correct:false},
    {response_id:1, question_id:71, response:`myArray.count`, is_correct:false},
    {response_id:2, question_id:71, response:`myArray.length`, is_correct:true},
    {response_id:3, question_id:71, response:`length(myArray)`, is_correct:false},
    {response_id:4, question_id:71, response:`myArray.size`, is_correct:false},
    {response_id:1, question_id:72, response:`The current function`, is_correct:false},
    {response_id:2, question_id:72, response:`The global object`, is_correct:true},
    {response_id:3, question_id:72, response:`The parent object`, is_correct:false},
    {response_id:4, question_id:72, response:`The HTML document`, is_correct:false},
    {response_id:1, question_id:73, response:`array.remove(index)`, is_correct:false},
    {response_id:2, question_id:73, response:`array.splice(index, 1)`, is_correct:true},
    {response_id:3, question_id:73, response:`array.pop()`, is_correct:false},
    {response_id:4, question_id:73, response:`array.delete(index)`, is_correct:false},
    {response_id:1, question_id:74, response:`A built-in JavaScript feature for controlling access to variables`, is_correct:false},
    {response_id:2, question_id:74, response:`A way to create private variables in a function`, is_correct:true},
    {response_id:3, question_id:74, response:`A special type of loop`, is_correct:false},
    {response_id:4, question_id:74, response:`A method for handling exceptions`, is_correct:false},
    {response_id:1, question_id:75, response:`Converts a JSON string into a JavaScript object`, is_correct:true},
    {response_id:2, question_id:75, response:`Parses a JavaScript object into a JSON string`, is_correct:false},
    {response_id:3, question_id:75, response:`Converts a JavaScript object into a JSON array`, is_correct:false},
    {response_id:4, question_id:75, response:`Encodes a JavaScript object`, is_correct:false},
    {response_id:1, question_id:76, response:`break;`, is_correct:true},
    {response_id:2, question_id:76, response:`continue;`, is_correct:false},
    {response_id:3, question_id:76, response:`return;`, is_correct:false},
    {response_id:4, question_id:76, response:`stop;`, is_correct:false},
    {response_id:1, question_id:77, response:`array.sort()`, is_correct:true},
    {response_id:2, question_id:77, response:`array.order()`, is_correct:false},
    {response_id:3, question_id:77, response:`array.sortElements()`, is_correct:false},
    {response_id:4, question_id:77, response:`array.arrange()`, is_correct:false},
    {response_id:1, question_id:78, response:`To store data on a remote server`, is_correct:false},
    {response_id:2, question_id:78, response:`To store data on the client's device for future sessions`, is_correct:true},
    {response_id:3, question_id:78, response:`To store temporary data during a function's execution`, is_correct:false},
    {response_id:4, question_id:78, response:`To store data in a cookie`, is_correct:false},
    {response_id:1, question_id:79, response:`A function that is called when an error occurs`, is_correct:false},
    {response_id:2, question_id:79, response:`A function passed as an argument to another function, to be executed later`, is_correct:true},
    {response_id:3, question_id:79, response:`A function that returns another function`, is_correct:false},
    {response_id:4, question_id:79, response:`A function used to call other functions`, is_correct:false},
    {response_id:1, question_id:80, response:`#`, is_correct:false},
    {response_id:2, question_id:80, response:`//`, is_correct:true},
    {response_id:3, question_id:80, response:`/* */`, is_correct:false},
    {response_id:4, question_id:80, response:`<!-- -->`, is_correct:false},
    {response_id:1, question_id:81, response:`A JavaScript framework for building web applications`, is_correct:false},
    {response_id:2, question_id:81, response:`A JavaScript library for building user interfaces`, is_correct:true},
    {response_id:3, question_id:81, response:`A server-side rendering framework`, is_correct:false},
    {response_id:4, question_id:81, response:`A database management system`, is_correct:false},
    {response_id:1, question_id:82, response:`Google`, is_correct:false},
    {response_id:2, question_id:82, response:`Facebook`, is_correct:true},
    {response_id:3, question_id:82, response:`Microsoft`, is_correct:false},
    {response_id:4, question_id:82, response:`Twitter`, is_correct:false},
    {response_id:1, question_id:83, response:`JavaScript Extra`, is_correct:false},
    {response_id:2, question_id:83, response:`JavaScript XML`, is_correct:true},
    {response_id:3, question_id:83, response:`JavaScript XSL`, is_correct:false},
    {response_id:4, question_id:83, response:`JavaScript Extension`, is_correct:false},
    {response_id:1, question_id:84, response:`To update the component's state`, is_correct:false},
    {response_id:2, question_id:84, response:`To render the component's UI`, is_correct:true},
    {response_id:3, question_id:84, response:`To define component props`, is_correct:false},
    {response_id:4, question_id:84, response:`To define component methods`, is_correct:false},
    {response_id:1, question_id:85, response:`A JavaScript function or class that returns JSX`, is_correct:true},
    {response_id:2, question_id:85, response:`A built-in HTML element`, is_correct:false},
    {response_id:3, question_id:85, response:`A Redux action`, is_correct:false},
    {response_id:4, question_id:85, response:`A CSS styling module`, is_correct:false},
    {response_id:1, question_id:86, response:`A lightweight version of the actual DOM`, is_correct:true},
    {response_id:2, question_id:86, response:`A component used for routing`, is_correct:false},
    {response_id:3, question_id:86, response:`A data store for global state management`, is_correct:false},
    {response_id:4, question_id:86, response:`A testing library for React`, is_correct:false},
    {response_id:1, question_id:87, response:`To store data that can be passed down to child components`, is_correct:false},
    {response_id:2, question_id:87, response:`To manage the component's internal data and reactivity`, is_correct:true},
    {response_id:3, question_id:87, response:`To define the component's initial props`, is_correct:false},
    {response_id:4, question_id:87, response:`To control the component's CSS styles`, is_correct:false},
    {response_id:1, question_id:88, response:`Using Redux`, is_correct:false},
    {response_id:2, question_id:88, response:`By setting a global variable`, is_correct:false},
    {response_id:3, question_id:88, response:`Through props`, is_correct:true},
    {response_id:4, question_id:88, response:`Using the setState() method`, is_correct:false},
    {response_id:1, question_id:89, response:`A component that is managed by a state container like Redux`, is_correct:false},
    {response_id:2, question_id:89, response:`A component that doesn't have any state`, is_correct:true},
    {response_id:3, question_id:89, response:`A component that relies on the DOM for state management`, is_correct:false},
    {response_id:4, question_id:89, response:`A component that manages its state internally`, is_correct:false},
    {response_id:1, question_id:90, response:`To update the component's state`, is_correct:false},
    {response_id:2, question_id:90, response:`To render the component's UI`, is_correct:false},
    {response_id:3, question_id:90, response:`To perform tasks after the component has been mounted to the DOM`, is_correct:true},
    {response_id:4, question_id:90, response:`To define component props`, is_correct:false},
    {response_id:1, question_id:91, response:`JSX`, is_correct:false},
    {response_id:2, question_id:91, response:`Props`, is_correct:false},
    {response_id:3, question_id:91, response:`Hooks`, is_correct:true},
    {response_id:4, question_id:91, response:`HOCs (Higher-Order Components)`, is_correct:false},
    {response_id:1, question_id:92, response:`To manage component state`, is_correct:false},
    {response_id:2, question_id:92, response:`To handle routing`, is_correct:false},
    {response_id:3, question_id:92, response:`To manage global application state`, is_correct:true},
    {response_id:4, question_id:92, response:`To define CSS styles`, is_correct:false},
    {response_id:1, question_id:93, response:`To update the component's state`, is_correct:false},
    {response_id:2, question_id:93, response:`To define component props`, is_correct:false},
    {response_id:3, question_id:93, response:`To manage state in a functional component`, is_correct:true},
    {response_id:4, question_id:93, response:`To create class-based components`, is_correct:false},
    {response_id:1, question_id:94, response:`<Route path="/:id" />`, is_correct:false},
    {response_id:2, question_id:94, response:`<Route path="/*" />`, is_correct:false},
    {response_id:3, question_id:94, response:`<Route path="*" />`, is_correct:true},
    {response_id:4, question_id:94, response:`<Route path="/" />`, is_correct:false},
    {response_id:1, question_id:95, response:`To define component props`, is_correct:false},
    {response_id:2, question_id:95, response:`To create a new array of elements with modified data`, is_correct:true},
    {response_id:3, question_id:95, response:`To filter the list based on specific criteria`, is_correct:false},
    {response_id:4, question_id:95, response:`To add event listeners to list items`, is_correct:false},
    {response_id:1, question_id:96, response:`By using the shouldComponentUpdate lifecycle method`, is_correct:true},
    {response_id:2, question_id:96, response:`By using the render method`, is_correct:false},
    {response_id:3, question_id:96, response:`By setting this.shouldUpdate = false`, is_correct:false},
    {response_id:4, question_id:96, response:`React components always re-render automatically`, is_correct:false},
    {response_id:1, question_id:97, response:`It sets the color of each element in the list`, is_correct:false},
    {response_id:2, question_id:97, response:`It uniquely identifies each element in the list and helps React update efficiently`, is_correct:true},
    {response_id:3, question_id:97, response:`It defines the order in which elements are rendered`, is_correct:false},
    {response_id:4, question_id:97, response:`It controls the visibility of each element`, is_correct:false},
    {response_id:1, question_id:98, response:`React Inspector`, is_correct:false},
    {response_id:2, question_id:98, response:`React DevTools`, is_correct:true},
    {response_id:3, question_id:98, response:`React Debugger`, is_correct:false},
    {response_id:4, question_id:98, response:`React Explorer`, is_correct:false},
    {response_id:1, question_id:99, response:`To define component props`, is_correct:false},
    {response_id:2, question_id:99, response:`To perform cleanup tasks before a component is removed from the DOM`, is_correct:true},
    {response_id:3, question_id:99, response:`To update the component's state`, is_correct:false},
    {response_id:4, question_id:99, response:`To render the component's UI`, is_correct:false},
    {response_id:1, question_id:100, response:`React Forms`, is_correct:false},
    {response_id:2, question_id:100, response:`React Formik`, is_correct:true},
    {response_id:3, question_id:100, response:`React Redux Forms`, is_correct:false},
    {response_id:4, question_id:100, response:`React Formify`, is_correct:false},
    {response_id:1, question_id:101, response:`Structured Query Language`, is_correct:true},
    {response_id:2, question_id:101, response:`System Query Language`, is_correct:false},
    {response_id:3, question_id:101, response:`Simple Query Language`, is_correct:false},
    {response_id:4, question_id:101, response:`Secondary Query Language`, is_correct:false},
    {response_id:1, question_id:102, response:`SELECT *`, is_correct:true},
    {response_id:2, question_id:102, response:`SELECT ALL`, is_correct:false},
    {response_id:3, question_id:102, response:`SELECT COLUMNS`, is_correct:false},
    {response_id:4, question_id:102, response:`SELECT FIELDS`, is_correct:false},
    {response_id:1, question_id:103, response:`GROUP BY`, is_correct:false},
    {response_id:2, question_id:103, response:`ORDER BY`, is_correct:false},
    {response_id:3, question_id:103, response:`WHERE`, is_correct:true},
    {response_id:4, question_id:103, response:`HAVING`, is_correct:false},
    {response_id:1, question_id:104, response:`To create a new table`, is_correct:false},
    {response_id:2, question_id:104, response:`To filter records`, is_correct:false},
    {response_id:3, question_id:104, response:`To combine rows from two or more tables`, is_correct:true},
    {response_id:4, question_id:104, response:`To sort data`, is_correct:false},
    {response_id:1, question_id:105, response:`VARCHAR`, is_correct:false},
    {response_id:2, question_id:105, response:`INT`, is_correct:false},
    {response_id:3, question_id:105, response:`DATE`, is_correct:true},
    {response_id:4, question_id:105, response:`BOOLEAN`, is_correct:false},
    {response_id:1, question_id:106, response:`INSERT`, is_correct:false},
    {response_id:2, question_id:106, response:`MODIFY`, is_correct:false},
    {response_id:3, question_id:106, response:`UPDATE`, is_correct:true},
    {response_id:4, question_id:106, response:`ALTER`, is_correct:false},
    {response_id:1, question_id:107, response:`To identify a unique record in the table`, is_correct:true},
    {response_id:2, question_id:107, response:`To link two tables together`, is_correct:false},
    {response_id:3, question_id:107, response:`To store binary data`, is_correct:false},
    {response_id:4, question_id:107, response:`To group rows together`, is_correct:false},
    {response_id:1, question_id:108, response:`ADD RECORD`, is_correct:false},
    {response_id:2, question_id:108, response:`INSERT INTO`, is_correct:true},
    {response_id:3, question_id:108, response:`CREATE RECORD`, is_correct:false},
    {response_id:4, question_id:108, response:`UPDATE TABLE`, is_correct:false},
    {response_id:1, question_id:109, response:`To limit the number of columns returned in a query`, is_correct:true},
    {response_id:2, question_id:109, response:`To limit the number of rows returned in a query`, is_correct:false},
    {response_id:3, question_id:109, response:`To limit the number of tables used in a query`, is_correct:false},
    {response_id:4, question_id:109, response:`To limit the number of conditions in a query`, is_correct:false},
    {response_id:1, question_id:110, response:`The average value of a column`, is_correct:false},
    {response_id:2, question_id:110, response:`The total number of rows in a table`, is_correct:true},
    {response_id:3, question_id:110, response:`The sum of all values in a column`, is_correct:false},
    {response_id:4, question_id:110, response:`The maximum value in a column`, is_correct:false},
    {response_id:1, question_id:111, response:`DELETE DATA`, is_correct:false},
    {response_id:2, question_id:111, response:`DELETE TABLE`, is_correct:false},
    {response_id:3, question_id:111, response:`REMOVE DATA`, is_correct:false},
    {response_id:4, question_id:111, response:`DELETE FROM`, is_correct:true},
    {response_id:1, question_id:112, response:`Sorts the result set in ascending order`, is_correct:true},
    {response_id:2, question_id:112, response:`Sorts the result set in descending order`, is_correct:false},
    {response_id:3, question_id:112, response:`Filters the result set`, is_correct:false},
    {response_id:4, question_id:112, response:`Groups the result set`, is_correct:false},
    {response_id:1, question_id:113, response:`DELETE TABLE`, is_correct:false},
    {response_id:2, question_id:113, response:`REMOVE TABLE`, is_correct:false},
    {response_id:3, question_id:113, response:`DROP TABLE`, is_correct:true},
    {response_id:4, question_id:113, response:`ERASE TABLE`, is_correct:false},
    {response_id:1, question_id:114, response:`To delete duplicate rows from a table`, is_correct:false},
    {response_id:2, question_id:114, response:`To select only unique values from a column`, is_correct:true},
    {response_id:3, question_id:114, response:`To sort the result set in ascending order`, is_correct:false},
    {response_id:4, question_id:114, response:`To create a new table`, is_correct:false},
    {response_id:1, question_id:115, response:`MAX()`, is_correct:true},
    {response_id:2, question_id:115, response:`MIN()`, is_correct:false},
    {response_id:3, question_id:115, response:`AVG()`, is_correct:false},
    {response_id:4, question_id:115, response:`SUM()`, is_correct:false},
    {response_id:1, question_id:116, response:`80`, is_correct:false},
    {response_id:2, question_id:116, response:`3306`, is_correct:true},
    {response_id:3, question_id:116, response:`22`, is_correct:false},
    {response_id:4, question_id:116, response:`443`, is_correct:false},
    {response_id:1, question_id:117, response:`MODIFY TABLE`, is_correct:false},
    {response_id:2, question_id:117, response:`ALTER TABLE`, is_correct:true},
    {response_id:3, question_id:117, response:`UPDATE TABLE`, is_correct:false},
    {response_id:4, question_id:117, response:`CHANGE TABLE`, is_correct:false},
    {response_id:1, question_id:118, response:`To filter results based on a specific value`, is_correct:false},
    {response_id:2, question_id:118, response:`To compare two columns`, is_correct:false},
    {response_id:3, question_id:118, response:`To search for a specified pattern in a column`, is_correct:true},
    {response_id:4, question_id:118, response:`To combine multiple columns`, is_correct:false},
    {response_id:1, question_id:119, response:`CREATE TABLE`, is_correct:false},
    {response_id:2, question_id:119, response:`CREATE DATABASE`, is_correct:true},
    {response_id:3, question_id:119, response:`INSERT DATABASE`, is_correct:false},
    {response_id:4, question_id:119, response:`ADD DATABASE`, is_correct:false},
    {response_id:1, question_id:120, response:`A primary key in another table`, is_correct:true},
    {response_id:2, question_id:120, response:`A unique constraint in a table`, is_correct:false},
    {response_id:3, question_id:120, response:`A column that cannot contain NULL values`, is_correct:false},
    {response_id:4, question_id:120, response:`A column used for ordering rows`, is_correct:false},
  ]);
};