/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('responses').del();
  await knex('responses').insert([
    { response_id: 1, question_id: 1, response: `Hyperlink Text Markup Language`, is_correct: false },
    { response_id: 2, question_id: 1, response: `Hypertext Transfer Markup Language`, is_correct: true },
    { response_id: 3, question_id: 1, response: `Hyper Text Makeup Language`, is_correct: false },
    { response_id: 4, question_id: 1, response: `High-Level Text Markup Language`, is_correct: false },
    { response_id: 1, question_id: 2, response: `<header>`, is_correct: false },
    { response_id: 2, question_id: 2, response: ` <body>`, is_correct: false },
    { response_id: 3, question_id: 2, response: `<html>`, is_correct: true },
    { response_id: 4, question_id: 2, response: `<main>`, is_correct: false },
    { response_id: 1, question_id: 3, response: `<ul>`, is_correct: false },
    { response_id: 2, question_id: 3, response: `<list>`, is_correct: false },
    { response_id: 3, question_id: 3, response: `<ol>`, is_correct: true },
    { response_id: 4, question_id: 3, response: `<li>`, is_correct: false },
    { response_id: 1, question_id: 4, response: `<link>`, is_correct: true },
    { response_id: 2, question_id: 4, response: `<a>`, is_correct: false },
    { response_id: 3, question_id: 4, response: `<href>`, is_correct: false },
    { response_id: 4, question_id: 4, response: ` <url>`, is_correct: false },
    { response_id: 1, question_id: 5, response: ` To define a paragraph`, is_correct: false },
    { response_id: 2, question_id: 5, response: `To provide metadata about the document`, is_correct: true },
    { response_id: 3, question_id: 5, response: `To create a line break`, is_correct: false },
    { response_id: 4, question_id: 5, response: `To define a hyperlink`, is_correct: false },
    { response_id: 1, question_id: 6, response: `<br>`, is_correct: true },
    { response_id: 2, question_id: 6, response: `<lb>`, is_correct: false },
    { response_id: 3, question_id: 6, response: `<newline>`, is_correct: false },
    { response_id: 4, question_id: 6, response: `<break>`, is_correct: false },
    { response_id: 1, question_id: 7, response: `<!-- This is a comment -->`, is_correct: true },
    { response_id: 2, question_id: 7, response: `// This is a comment //`, is_correct: false },
    { response_id: 3, question_id: 7, response: `* This is a comment */`, is_correct: false },
    { response_id: 4, question_id: 7, response: `** This is a comment **`, is_correct: false },
    { response_id: 1, question_id: 8, response: `<header>`, is_correct: false },
    { response_id: 2, question_id: 8, response: ` <title>`, is_correct: true },
    { response_id: 3, question_id: 8, response: ` <h1>`, is_correct: false },
    { response_id: 4, question_id: 8, response: `<head>`, is_correct: false },
    { response_id: 1, question_id: 9, response: `To insert an image`, is_correct: false },
    { response_id: 2, question_id: 9, response: `To create a clickable button`, is_correct: false },
    { response_id: 3, question_id: 9, response: `To embed external content like a video or map`, is_correct: true },
    { response_id: 4, question_id: 9, response: `To define a list`, is_correct: false },
    { response_id: 1, question_id: 10, response: `charset`, is_correct: true },
    { response_id: 2, question_id: 10, response: `encoding`, is_correct: false },
    { response_id: 3, question_id: 10, response: `content-type`, is_correct: false },
    { response_id: 4, question_id: 10, response: `language`, is_correct: false },
    { response_id: 1, question_id: 11, response: `<email>`, is_correct: false },
    { response_id: 2, question_id: 11, response: `<mail>`, is_correct: false },
    { response_id: 3, question_id: 11, response: `<a href="mailto:email@example.com">`, is_correct: true },
    { response_id: 4, question_id: 11, response: `<link href="email@example.com">`, is_correct: false },
    { response_id: 1, question_id: 12, response: `<td>`, is_correct: false },
    { response_id: 2, question_id: 12, response: `<tr>`, is_correct: true },
    { response_id: 3, question_id: 12, response: `<table>`, is_correct: false },
    { response_id: 4, question_id: 12, response: `<th>`, is_correct: false },
    { response_id: 1, question_id: 13, response: `To define a division or section of a webpage`, is_correct: true },
    { response_id: 2, question_id: 13, response: `To create a hyperlink`, is_correct: false },
    { response_id: 3, question_id: 13, response: `To insert a line break`, is_correct: false },
    { response_id: 4, question_id: 13, response: `To define a list`, is_correct: false },
    { response_id: 1, question_id: 14, response: `<ul>`, is_correct: true },
    { response_id: 2, question_id: 14, response: `<list>`, is_correct: false },
    { response_id: 3, question_id: 14, response: `<ol>`, is_correct: false },
    { response_id: 4, question_id: 14, response: `<li>`, is_correct: false },
    { response_id: 1, question_id: 15, response: `<line>`, is_correct: false },
    { response_id: 2, question_id: 15, response: `<break>`, is_correct: false },
    { response_id: 3, question_id: 15, response: `<br>`, is_correct: true },
    { response_id: 4, question_id: 15, response: `<newline>`, is_correct: false },
    { response_id: 1, question_id: 16, response: `alt`, is_correct: true },
    { response_id: 2, question_id: 16, response: `text`, is_correct: false },
    { response_id: 3, question_id: 16, response: `description`, is_correct: false },
    { response_id: 4, question_id: 16, response: `img-alt`, is_correct: false },
    { response_id: 1, question_id: 17, response: `It defines a section of the webpage.`, is_correct: false },
    { response_id: 2, question_id: 17, response: `It defines a hyperlink.`, is_correct: false },
    { response_id: 3, question_id: 17, response: ` It creates a clickable button.`, is_correct: false },
    { response_id: 4, question_id: 17, response: `It defines an interactive form for user input.`, is_correct: true },
    { response_id: 1, question_id: 18, response: `<head>`, is_correct: false },
    { response_id: 2, question_id: 18, response: `<main>`, is_correct: false },
    { response_id: 3, question_id: 18, response: `<body>`, is_correct: true },
    { response_id: 4, question_id: 18, response: `<section>`, is_correct: false },
    { response_id: 1, question_id: 19, response: `To create a radio button`, is_correct: false },
    { response_id: 2, question_id: 19, response: `To insert a text input field`, is_correct: false },
    { response_id: 3, question_id: 19, response: `To create a checkbox for multiple selections`, is_correct: true },
    { response_id: 4, question_id: 19, response: `To define a dropdown menu`, is_correct: false },
    { response_id: 1, question_id: 20, response: `<ul>`, is_correct: false },
    { response_id: 2, question_id: 20, response: `<list>`, is_correct: false },
    { response_id: 3, question_id: 20, response: `<ol>`, is_correct: true },
    { response_id: 4, question_id: 20, response: `<li>`, is_correct: false }
  ]);
};