/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('responses').del();
  await knex('responses').insert([
    {response_id:1, question_id:1, response:`Hyperlink Text Markup Language`, is_correct:false},
    {response_id:2, question_id:1, response:`Hypertext Transfer Markup Language`, is_correct:true},
    {response_id:3, question_id:1, response:`Hyper Text Makeup Language`, is_correct:false},
    {response_id:4, question_id:1, response:`High-Level Text Markup Language`, is_correct:false},
    {response_id:1, question_id:2, response:`"header"`, is_correct:false},
    {response_id:2, question_id:2, response:` "body"`, is_correct:false},
    {response_id:3, question_id:2, response:`"html"`, is_correct:true},
    {response_id:4, question_id:2, response:`"main"`, is_correct:false},
    {response_id:1, question_id:3, response:`"ul"`, is_correct:false},
    {response_id:2, question_id:3, response:`"list"`, is_correct:false},
    {response_id:3, question_id:3, response:`"ol"`, is_correct:true},
    {response_id:4, question_id:3, response:`"li"`, is_correct:false},
    {response_id:1, question_id:4, response:`"link"`, is_correct:true},
    {response_id:2, question_id:4, response:`"a"`, is_correct:false},
    {response_id:3, question_id:4, response:`"href"`, is_correct:false},
    {response_id:4, question_id:4, response:` "url"`, is_correct:false},
    {response_id:1, question_id:5, response:` To define a paragraph`, is_correct:false},
    {response_id:2, question_id:5, response:`To provide metadata about the document`, is_correct:true},
    {response_id:3, question_id:5, response:`To create a line break`, is_correct:false},
    {response_id:4, question_id:5, response:`To define a hyperlink`, is_correct:false},
    {response_id:1, question_id:6, response:`"br"`, is_correct:true},
    {response_id:2, question_id:6, response:`"lb"`, is_correct:false},
    {response_id:3, question_id:6, response:`"newline"`, is_correct:false},
    {response_id:4, question_id:6, response:`"break"`, is_correct:false},
    {response_id:1, question_id:7, response:`"!-- This is a comment --"`, is_correct:true},
    {response_id:2, question_id:7, response:`// This is a comment //`, is_correct:false},
    {response_id:3, question_id:7, response:`* This is a comment */`, is_correct:false},
    {response_id:4, question_id:7, response:`** This is a comment **`, is_correct:false},
    {response_id:1, question_id:8, response:`"header"`, is_correct:false},
    {response_id:2, question_id:8, response:` "title"`, is_correct:true},
    {response_id:3, question_id:8, response:` "h1"`, is_correct:false},
    {response_id:4, question_id:8, response:`"head"`, is_correct:false},
    {response_id:1, question_id:9, response:`To insert an image`, is_correct:false},
    {response_id:2, question_id:9, response:`To create a clickable button`, is_correct:false},
    {response_id:3, question_id:9, response:`To embed external content like a video or map`, is_correct:true},
    {response_id:4, question_id:9, response:`To define a list`, is_correct:false},
    {response_id:1, question_id:10, response:`charset`, is_correct:true},
    {response_id:2, question_id:10, response:`encoding`, is_correct:false},
    {response_id:3, question_id:10, response:`content-type`, is_correct:false},
    {response_id:4, question_id:10, response:`language`, is_correct:false},
    {response_id:1, question_id:11, response:`"email"`, is_correct:false},
    {response_id:2, question_id:11, response:`"mail"`, is_correct:false},
    {response_id:3, question_id:11, response:`"a href="mailto:email@example.com""`, is_correct:true},
    {response_id:4, question_id:11, response:`"link href="email@example.com""`, is_correct:false},
    {response_id:1, question_id:12, response:`"td"`, is_correct:false},
    {response_id:2, question_id:12, response:`"tr"`, is_correct:true},
    {response_id:3, question_id:12, response:`"table"`, is_correct:false},
    {response_id:4, question_id:12, response:`"th"`, is_correct:false},
    {response_id:1, question_id:13, response:`To define a division or section of a webpage`, is_correct:true},
    {response_id:2, question_id:13, response:`To create a hyperlink`, is_correct:false},
    {response_id:3, question_id:13, response:`To insert a line break`, is_correct:false},
    {response_id:4, question_id:13, response:`To define a list`, is_correct:false},
    {response_id:1, question_id:14, response:`"ul"`, is_correct:true},
    {response_id:2, question_id:14, response:`"list"`, is_correct:false},
    {response_id:3, question_id:14, response:`"ol"`, is_correct:false},
    {response_id:4, question_id:14, response:`"li"`, is_correct:false},
    {response_id:1, question_id:15, response:`"line"`, is_correct:false},
    {response_id:2, question_id:15, response:`"break"`, is_correct:false},
    {response_id:3, question_id:15, response:`"br"`, is_correct:true},
    {response_id:4, question_id:15, response:`"newline"`, is_correct:false},
    {response_id:1, question_id:16, response:`alt`, is_correct:true},
    {response_id:2, question_id:16, response:`text`, is_correct:false},
    {response_id:3, question_id:16, response:`description`, is_correct:false},
    {response_id:4, question_id:16, response:`img-alt`, is_correct:false},
    {response_id:1, question_id:17, response:`It defines a section of the webpage.`, is_correct:false},
    {response_id:2, question_id:17, response:`It defines a hyperlink.`, is_correct:false},
    {response_id:3, question_id:17, response:` It creates a clickable button.`, is_correct:false},
    {response_id:4, question_id:17, response:`It defines an interactive form for user input.`, is_correct:true},
    {response_id:1, question_id:18, response:`"head"`, is_correct:false},
    {response_id:2, question_id:18, response:`"main"`, is_correct:false},
    {response_id:3, question_id:18, response:`"body"`, is_correct:true},
    {response_id:4, question_id:18, response:`"section"`, is_correct:false},
    {response_id:1, question_id:19, response:`To create a radio button`, is_correct:false},
    {response_id:2, question_id:19, response:`To insert a text input field`, is_correct:false},
    {response_id:3, question_id:19, response:`To create a checkbox for multiple selections`, is_correct:true},
    {response_id:4, question_id:19, response:`To define a dropdown menu`, is_correct:false},
    {response_id:1, question_id:20, response:`"ul"`, is_correct:false},
    {response_id:2, question_id:20, response:`"list"`, is_correct:false},
    {response_id:3, question_id:20, response:`"ol"`, is_correct:true},
    {response_id:4, question_id:20, response:`"li"`, is_correct:false},
    {response_id:1, question_id:21, response:`Computer Style Sheets`, is_correct:false},
    {response_id:2, question_id:21, response:`Creative Style Sheets`, is_correct:false},
    {response_id:3, question_id:21, response:`Cascading Style Sheets`, is_correct:true},
    {response_id:4, question_id:21, response:`Complex Style Sheets`, is_correct:false},
    {response_id:1, question_id:22, response:`text-color`, is_correct:false},
    {response_id:2, question_id:22, response:`font-color`, is_correct:false},
    {response_id:3, question_id:22, response:`color`, is_correct:true},
    {response_id:4, question_id:22, response:`text-style`, is_correct:false},
    {response_id:1, question_id:23, response:`Using the "style" tag`, is_correct:false},
    {response_id:2, question_id:23, response:`Using the "link" tag`, is_correct:true},
    {response_id:3, question_id:23, response:`Using the "css" tag`, is_correct:false},
    {response_id:4, question_id:23, response:`Using the "external-css" tag`, is_correct:false},
    {response_id:1, question_id:24, response:`background-color`, is_correct:true},
    {response_id:2, question_id:24, response:`color-background`, is_correct:false},
    {response_id:3, question_id:24, response:`background-style`, is_correct:false},
    {response_id:4, question_id:24, response:`bgcolor`, is_correct:false},
    {response_id:1, question_id:25, response:`#element.example`, is_correct:false},
    {response_id:2, question_id:25, response:`.element#example`, is_correct:false},
    {response_id:3, question_id:25, response:`#example`, is_correct:true},
    {response_id:4, question_id:25, response:`.example`, is_correct:false},
    {response_id:1, question_id:26, response:`static`, is_correct:true},
    {response_id:2, question_id:26, response:`relative`, is_correct:false},
    {response_id:3, question_id:26, response:`absolute`, is_correct:false},
    {response_id:4, question_id:26, response:`fixed`, is_correct:false},
    {response_id:1, question_id:27, response:`margin`, is_correct:true},
    {response_id:2, question_id:27, response:`padding`, is_correct:false},
    {response_id:3, question_id:27, response:`border-spacing`, is_correct:false},
    {response_id:4, question_id:27, response:`spacing`, is_correct:false},
    {response_id:1, question_id:28, response:`font-weight`, is_correct:true},
    {response_id:2, question_id:28, response:`text-style`, is_correct:false},
    {response_id:3, question_id:28, response:`font-bold`, is_correct:false},
    {response_id:4, question_id:28, response:`bold-text`, is_correct:false},
    {response_id:1, question_id:29, response:`:first-child`, is_correct:true},
    {response_id:2, question_id:29, response:`:child-first`, is_correct:false},
    {response_id:3, question_id:29, response:`:first`, is_correct:false},
    {response_id:4, question_id:29, response:`:first-of-type`, is_correct:false},
    {response_id:1, question_id:30, response:`Separate them with a comma (,)`, is_correct:true},
    {response_id:2, question_id:30, response:`Separate them with a plus sign (+)`, is_correct:false},
    {response_id:3, question_id:30, response:`Separate them with a hyphen (-)`, is_correct:false},
    {response_id:4, question_id:30, response:`Separate them with a semicolon (;)`, is_correct:false},
    {response_id:1, question_id:31, response:`line-height`, is_correct:true},
    {response_id:2, question_id:31, response:`text-spacing`, is_correct:false},
    {response_id:3, question_id:31, response:`line-spacing`, is_correct:false},
    {response_id:4, question_id:31, response:`text-line`, is_correct:false},
    {response_id:1, question_id:32, response:`The order in which styles are applied`, is_correct:false},
    {response_id:2, question_id:32, response:`The size of text`, is_correct:false},
    {response_id:3, question_id:32, response:`Which style rules take precedence`, is_correct:true},
    {response_id:4, question_id:32, response:`The color of text`, is_correct:false},
    {response_id:1, question_id:33, response:`display: hidden`, is_correct:false},
    {response_id:2, question_id:33, response:`visibility: hidden`, is_correct:false},
    {response_id:3, question_id:33, response:`opacity: 0`, is_correct:false},
    {response_id:4, question_id:33, response:`display: none`, is_correct:true},
    {response_id:1, question_id:34, response:`shadow-effect`, is_correct:false},
    {response_id:2, question_id:34, response:`box-shadow`, is_correct:true},
    {response_id:3, question_id:34, response:`text-shadow`, is_correct:false},
    {response_id:4, question_id:34, response:`element-shadow`, is_correct:false},
    {response_id:1, question_id:35, response:`Makes text float on the water`, is_correct:false},
    {response_id:2, question_id:35, response:`Removes an element from the flow of the document`, is_correct:true},
    {response_id:3, question_id:35, response:`Changes the font style`, is_correct:false},
    {response_id:4, question_id:35, response:`Sets an element's position to fixed`, is_correct:false},
    {response_id:1, question_id:36, response:`flex-direction`, is_correct:false},
    {response_id:2, question_id:36, response:`order`, is_correct:true},
    {response_id:3, question_id:36, response:`flex-order`, is_correct:false},
    {response_id:4, question_id:36, response:`item-order`, is_correct:false},
    {response_id:1, question_id:37, response:`The size of an element`, is_correct:false},
    {response_id:2, question_id:37, response:`The position of an element relative to its parent`, is_correct:true},
    {response_id:3, question_id:37, response:`The font size`, is_correct:false},
    {response_id:4, question_id:37, response:`The color of text`, is_correct:false},
    {response_id:1, question_id:38, response:`text-align: center`, is_correct:false},
    {response_id:2, question_id:38, response:`margin: auto`, is_correct:false},
    {response_id:3, question_id:38, response:`align: center`, is_correct:false},
    {response_id:4, question_id:38, response:`display: center`, is_correct:true},
    {response_id:1, question_id:39, response:`border-curve`, is_correct:false},
    {response_id:2, question_id:39, response:`corner-radius`, is_correct:false},
    {response_id:3, question_id:39, response:`border-radius`, is_correct:true},
    {response_id:4, question_id:39, response:`rounded-border`, is_correct:false},
    {response_id:1, question_id:40, response:`To change the font size of text`, is_correct:false},
    {response_id:2, question_id:40, response:`To apply different styles based on the screen size or device`, is_correct:true},
    {response_id:3, question_id:40, response:`To change the background color of an element`, is_correct:false},
    {response_id:4, question_id:40, response:`To create animations`, is_correct:false},
    {response_id:1, question_id:41, response:`Sassy Cascading Style Sheets`, is_correct:true},
    {response_id:2, question_id:41, response:`Scalable Cascading Style Sheets`, is_correct:false},
    {response_id:3, question_id:41, response:`Simple Cascading Style Sheets`, is_correct:false},
    {response_id:4, question_id:41, response:`Styled Cascading Style Sheets`, is_correct:false},
    {response_id:1, question_id:42, response:`"{}"`, is_correct:true},
    {response_id:2, question_id:42, response:`"()"`, is_correct:false},
    {response_id:3, question_id:42, response:`"[]"`, is_correct:false},
    {response_id:4, question_id:42, response:`"&"`, is_correct:false},
    {response_id:1, question_id:43, response:`calc()`, is_correct:true},
    {response_id:2, question_id:43, response:`math()`, is_correct:false},
    {response_id:3, question_id:43, response:`calculate()`, is_correct:false},
    {response_id:4, question_id:43, response:`sum()`, is_correct:false},
    {response_id:1, question_id:44, response:`To include external JavaScript files`, is_correct:false},
    {response_id:2, question_id:44, response:`To include external CSS files`, is_correct:false},
    {response_id:3, question_id:44, response:`To include another SCSS file`, is_correct:true},
    {response_id:4, question_id:44, response:`To declare variables`, is_correct:false},
    {response_id:1, question_id:45, response:`Comments`, is_correct:false},
    {response_id:2, question_id:45, response:`Mixins`, is_correct:false},
    {response_id:3, question_id:45, response:`Variables`, is_correct:true},
    {response_id:4, question_id:45, response:`Functions`, is_correct:false},
    {response_id:1, question_id:46, response:`Variables`, is_correct:false},
    {response_id:2, question_id:46, response:`Mixins`, is_correct:true},
    {response_id:3, question_id:46, response:`Functions`, is_correct:false},
    {response_id:4, question_id:46, response:`Classes`, is_correct:false},
    {response_id:1, question_id:47, response:`To create a new class`, is_correct:false},
    {response_id:2, question_id:47, response:`To include external libraries`, is_correct:false},
    {response_id:3, question_id:47, response:`To share styles between selectors`, is_correct:true},
    {response_id:4, question_id:47, response:`To import images`, is_correct:false},
    {response_id:1, question_id:48, response:`Numbers`, is_correct:false},
    {response_id:2, question_id:48, response:`Lists`, is_correct:true},
    {response_id:3, question_id:48, response:`Strings`, is_correct:false},
    {response_id:4, question_id:48, response:`Colors`, is_correct:false},
    {response_id:1, question_id:49, response:`/* This is a comment */`, is_correct:true},
    {response_id:2, question_id:49, response:`// This is a comment`, is_correct:false},
    {response_id:3, question_id:49, response:` This is a comment`, is_correct:false},
    {response_id:4, question_id:49, response:`# This is a comment`, is_correct:false},
    {response_id:1, question_id:50, response:`It makes the variable immutable.`, is_correct:false},
    {response_id:2, question_id:50, response:`It sets a default value if the variable is undefined.`, is_correct:true},
    {response_id:3, question_id:50, response:`It creates a global variable.`, is_correct:false},
    {response_id:4, question_id:50, response:`It makes the variable inheritable.`, is_correct:false},
    {response_id:1, question_id:51, response:`"+"`, is_correct:true},
    {response_id:2, question_id:51, response:`"-"`, is_correct:false},
    {response_id:3, question_id:51, response:`"*"`, is_correct:false},
    {response_id:4, question_id:51, response:`"/"`, is_correct:false},
    {response_id:1, question_id:52, response:`A border with a color 10% darker than #3498db`, is_correct:true},
    {response_id:2, question_id:52, response:`A border with a color #3498db`, is_correct:false},
    {response_id:3, question_id:52, response:`A border with a color 10% lighter than #3498db`, is_correct:false},
    {response_id:4, question_id:52, response:`An error`, is_correct:false},
    {response_id:1, question_id:53, response:`To define a function`, is_correct:true},
    {response_id:2, question_id:53, response:`To create a loop`, is_correct:false},
    {response_id:3, question_id:53, response:`To include external stylesheets`, is_correct:false},
    {response_id:4, question_id:53, response:`To define a class`, is_correct:false},
    {response_id:1, question_id:54, response:`Define a loop`, is_correct:true},
    {response_id:2, question_id:54, response:`Import fonts`, is_correct:false},
    {response_id:3, question_id:54, response:`Create a new class`, is_correct:false},
    {response_id:4, question_id:54, response:`Define a mixin`, is_correct:false},
    {response_id:1, question_id:55, response:`random()`, is_correct:false},
    {response_id:2, question_id:55, response:`generateRandom()`, is_correct:false},
    {response_id:3, question_id:55, response:`rand()`, is_correct:true},
    {response_id:4, question_id:55, response:`randomNumber()`, is_correct:false},
    {response_id:1, question_id:56, response:`To define a variable`, is_correct:false},
    {response_id:2, question_id:56, response:`To create a loop`, is_correct:false},
    {response_id:3, question_id:56, response:`To conditionally apply styles`, is_correct:true},
    {response_id:4, question_id:56, response:`To include external files`, is_correct:false},
    {response_id:1, question_id:57, response:`Variables`, is_correct:false},
    {response_id:2, question_id:57, response:`Mixins`, is_correct:false},
    {response_id:3, question_id:57, response:`Nesting`, is_correct:true},
    {response_id:4, question_id:57, response:`Functions`, is_correct:false},
    {response_id:1, question_id:58, response:`@import "styles/mystyles";`, is_correct:false},
    {response_id:2, question_id:58, response:`@import "./mystyles";`, is_correct:false},
    {response_id:3, question_id:58, response:`@import "../styles/mystyles";`, is_correct:true},
    {response_id:4, question_id:58, response:`@import "mystyles.scss";`, is_correct:false},
    {response_id:1, question_id:59, response:`To define a variable`, is_correct:false},
    {response_id:2, question_id:59, response:`To create a loop`, is_correct:false},
    {response_id:3, question_id:59, response:`To apply styles based on screen size or media type`, is_correct:true},
    {response_id:4, question_id:59, response:`To include external files`, is_correct:false},
    {response_id:1, question_id:60, response:`Variables`, is_correct:false},
    {response_id:2, question_id:60, response:`Mixins`, is_correct:true},
    {response_id:3, question_id:60, response:`Functions`, is_correct:false},
    {response_id:4, question_id:60, response:`Classes`, is_correct:false},
  ]);
};